### ISSUE TITLE
找不到名为 'nonebot.adapters.cqhttp'的module

### ISSUE THREAD

**Issue by NtskwK** [InvoluteHell/Pallas-Bot#10]
我在安装好requirements里的内容后运行了它，但是遇到了这样的错误信息
>natsukawa@VM-4-6-ubuntu:~/Pallas-Bot$ python3 -m nb_cli run
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/natsukawa/.local/lib/python3.8/site-packages/nb_cli/__main__.py", line 4, in <module>
    main()
  File "/home/natsukawa/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/natsukawa/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/natsukawa/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/natsukawa/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/natsukawa/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/natsukawa/.local/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/home/natsukawa/.local/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/natsukawa/Pallas-Bot/./bot.py", line 5, in <module>
    from nonebot.adapters.cqhttp import Bot as CQHTTPBot
ModuleNotFoundError: No module named 'nonebot.adapters.cqhttp'

(非常抱歉，我不知道该如何在issues里插入图片)
我想可能是由于我没有正确填写config造成的，于是我尝试删除自带的config并使用go-cqhttp重新生成了一个新的再填写，可这似乎并没有什么作用。接着，我尝试使用nonebot2手册里的方法，也就是直接用  python bot.py  启动，但还是不起作用。
>  natsukawa@VM-4-6-ubuntu:~/Pallas-Bot$ python3 bot.py
Traceback (most recent call last):
  File "bot.py", line 5, in <module>
    from nonebot.adapters.cqhttp import Bot as CQHTTPBot
ModuleNotFoundError: No module named 'nonebot.adapters.cqhttp'

可能是我太笨了，完全没有意识到自己究竟是在哪一步犯傻了。
请问你可以给我一些有关于如何解决这个问题的提示吗？

**Comment by MistEO** [comment]
我也是 python 小白，没有遇到过这个错误 orz

感觉可能的尝试：
1. 试试用 `nb run` 来启动，因为我自己都是这样启动的
2. 自己新建一个 nb 项目，也选 gocq 相关配置，试试能启动吗？

**Comment by NtskwK** [comment]
非常感谢！
可能是因为配置的原因，服务器无法识别```nb```指令，于是我从头重新进行了配置（从部署python-dev开始）。
……
系统提示我requirements.txt的第3行和第21行是一样的，尽管看上去有些差别，但我还是删掉了21行才再次进行配置。
另外，我发现```nonebot_plugin_apscheduler```有的时候会因为```pyproject.toml```无法部署，我不清楚昨晚造成这个问题的原因是什么，但现在使用了```go-cqhttp```自动生成的config后，Pallas已经能成功接收```go-cqhttp```的信息了。```nb run```已经能启动了。
![屏幕截图 2022-03-12 162257](https://user-images.githubusercontent.com/88552976/158010203-14ab370f-eeaa-4c5f-a7ac-4561782a0b6e.png)
但由于多次测试“强行教“的时候，Pallas没有给出除上图以外的其他反应，我无法判断是学习次数不够还是出了什么其他的问题。于是我浏览了日志，发现了这一条
>03-12 15:53:18 [ERROR] nonebot | Failed to import "repeater"
我想这可能和出现的问题有关

**Comment by MistEO** [comment]
> 03-12 15:53:18 [ERROR] nonebot | Failed to import "repeater"

是有关的，这个就是牛牛复读的核心插件

启动的时候会依次加载各个插件，看看报啥错

**Comment by NtskwK** [comment]
现在，```repeater```所需的```nonebot_plugin_apscheduler```已经能正常安装，并且安装过程中没有报错。
我先运行了```go-cqhttp```,然后启动了```Pallas```，并在同时记录了Pallas的启动日志。其中我认为比较重要的部分大致如下
>03-12 23:55:54 [ERROR] nonebot | Failed to import "repeater"
Traceback (most recent call last):
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\handlers\deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Program\ChatBot\Pallas-Bot\.\bot.py", line 24, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\__init__.py", line 1089, in load_from_toml
    return load_all_plugins(set(plugins), set(plugin_dirs))
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\__init__.py", line 1031, in load_all_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\__init__.py", line 953, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 161, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 267, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Program\ChatBot\Pallas-Bot\bot/plugins\repeater\__init__.py", line 13, in <module>
    from .model import Chat, ChatData
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 267, in exec_module
    super().exec_module(module)
  File "E:\Program\ChatBot\Pallas-Bot\bot/plugins\repeater\model.py", line 26, in <module>
    message_mongo.create_index(name='time_index',
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\collection.py", line 2101, in create_index
    return self.__create_indexes([index], session, **cmd_options)[0]
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\collection.py", line 1961, in __create_indexes
    with self._socket_for_writes(session) as sock_info:
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\collection.py", line 198, in _socket_for_writes
    return self.__database.client._socket_for_writes(session)
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\mongo_client.py", line 1356, in _socket_for_writes
    server = self._select_server(writable_server_selector, session)
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\mongo_client.py", line 1346, in _select_server
    server = topology.select_server(server_selector)
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\topology.py", line 244, in select_server
    return random.choice(self.select_servers(selector,
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\topology.py", line 202, in select_servers
    server_descriptions = self._select_servers_loop(
  File "C:\Users\11240\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [WinError 10061] 由于目标计算机积极拒绝，无法连接。, Timeout: 30s, Topology Description: <TopologyDescription id: 622cc26bc2bf6195f411faa2, topology_type: Single, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')>]>

全部的日志总共有400行左右，但大部分似乎都是因为Pallas与```go-cqhttp```对接超时后进行重试产生的。（尽管后来对接成功了）
我搞不懂这部分提示当中的线索。完整的日志内容我会在稍后发到你的hotmail邮箱

**Comment by MistEO** [comment]
你是不是没有配置和启动 MongoDB_(:з」∠)_

**Comment by MistEO** [comment]
Windows 可以参考 [这个](https://www.runoob.com/mongodb/mongodb-window-install.html)，或者搜索别的教程

**Comment by NtskwK** [comment]
我重新检查了```MongoDB```的配置情况，它之前似乎没有成功被写进PATH中🦁
（发生的具体原因可能和之前```nb```无法被识别类似）
于是在修复并排查了其他问题后,Pallas已经能正常运行了！
非常感谢您的帮助！
